version: '3'
services:
   db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgresUser
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
   src:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--","go", "run", "main.go"]
    volumes:
      - .:/go/src
    ports:
      - "8080:8080"
    depends_on:
      - db
   pgadmin4:
    ports:
      - "5050:5050"
    environment: 
      SERVER_MODE : 'false'
    image: chorss/docker-pgadmin4
    volumes:
        - ./data/pgadmin4:/data/config
